'use server';

import { LoginSchema } from '@/schemas';
import { z } from 'zod';
import { AuthError } from 'next-auth';

import { signIn } from '@/auth';
import { DEFAULT_LOGIN_REDIRECT } from '@/routes';
import { generateVerificationToken } from '@/lib/tokens';
import { getUserByEmail } from '@/data/user';
import { sendVerificationEmail } from '@/lib/nodemail-transport';

export const login = async (
  values: z.infer<typeof LoginSchema>,
  callbackUrl?: string
) => {
  const validatedFields = LoginSchema.safeParse(values);

  if (!validatedFields.success) {
    return { error: 'Invalid fields' };
  }

  const { email, password } = validatedFields.data;

  const existingUser = await getUserByEmail(email);
  if (!existingUser || !existingUser.email || !existingUser.password) {
    return { error: 'Email does not exist' };
  }
  if (!existingUser.emailVerified) {
    const verificationToken = await generateVerificationToken(
      existingUser.email
    );

    try {
      // await sendVerificationEmail(
      //   verificationToken.email,
      //   verificationToken.token
      // );
      console.log('token verification');
    } catch (error) {
      return { error: 'Verification email not sent!' };
    }

    return { success: 'Confimation email sent again . Pease Check !' };
  }

  try {
    await signIn('credentials', {
      email,
      password,
      redirectTo: callbackUrl || DEFAULT_LOGIN_REDIRECT,
    });
  } catch (error) {
    if (error instanceof AuthError) {
      switch (error.type) {
        case 'CallbackRouteError':
        case 'CredentialsSignin':
        case 'AccessDenied':
          return { error: 'invalid credentials' };

        default:
          return { error: 'Something went wrong' };
      }
    }
    throw error;
  }
};
